Table ContactInfo {
  id int [PK]
  phone int
  address varchar
  email varchar
  website varchar
}

Table Business {
  id int [PK, ref: <> FarmersMarket.id]
  contact int [ref: > ContactInfo.id]
  description varchar
}

Table FarmersMarket {
  id int [PK]
  isSnapFriendly bool
  name varchar
  contact int [ref: > ContactInfo.id]
}

Table BusinessRepresentative {
  id int [PK]
  name varchar
  businessId int [ref: > Business.id]
}
