enum month {
    January
    February
    March
    April
    May
    June
    July
    August
    September
    October
    November
    December
}

enum day {
  Monday
  Tuesday
  Wednesday
  Thursday
  Friday
  Saturday
  Sunday
}

Table ContactInfo {
  id int [PK]
  phone int
  address varchar
  email varchar
  website varchar
}

Table Business {
  id int [PK]
  contact int [ref: > ContactInfo.id]
  description varchar
}

Table ManyBusinessManyFarmersMarkets{
  businessId int [PK, ref: - Business.id]
  farmersMarketId int [PK, ref: - FarmersMarket.id] 
}

Table OperatingDays {
  id int [PK]
  marketId int [PK, ref: > FarmersMarket.id]
  Day day
}

Table OperatingMonths {
  marketId int [PK, ref: > FarmersMarket.id]
  Month month
}

Table OperatingHours {
  dayId int [PK, ref: > OperatingDays.id]
  from int [PK]
  to int [PK]
  timezone string
}

Table FarmersMarket {
  id int [PK]
  isSnapFriendly bool
  name varchar
  contact int [ref: > ContactInfo.id]
}

Table BusinessRepresentative {
  id int [PK]
  name varchar
  businessId int [ref: > Business.id]
}
