openapi: 3.0.3
info:
  title: Farmer's Markets - OpenAPI 3.0
  description: |-
    Does cool stuff
  version: 1.0.11
tags:
  - name: FarmersMarkets
    description: Get all Farmers Markets or farmers markets by state or zipcode that accept EBT/SNAP
paths:
  /farmersMarkets:
    get:
      tags:
        - farmersMarkets
      summary: Gets all farmers markets
      operationId: GetFarmersMarkets
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ApiResponse'          
        '500':
          description: Unexpected error occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'     
  /farmersMarkets/{zipCode}:
    get:
      tags:
        - farmersMarkets
      summary: Gets all Farmers Markets with 25 miles
      description: Returns a collecction of farmers markets
      operationId: GetFarmersMarketsByZipcode
      parameters:
        - name: zipCode
          in: path
          description: zip code for user
          required: true
          schema:
            type: string
            minLength: 5
            maxLength: 5
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'   
        '400':
          description: Invalid Zip Code
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'     
        '404':
          description: No Farmers Markets taht accepts SNAP
        '500':
          description: Unexpected error occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'     
  /farmersMarkets/{state}:
    get:
      tags:
        - farmersMarkets
      summary: Gets all Farmers Markets with within the specified state
      description: Returns a collecction of farmers markets
      operationId: GetFarmersMarketsByState
      parameters:
        - name: state
          in: path
          description: state for user
          required: true
          schema:
            type: string
            minLength: 2
            maxLength: 2
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'          
        '400':
          description: Invalid State
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'     
        '404':
          description: No Farmers Markets taht accepts SNAP
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'     
        '500':
          description: Unexpected error occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'     
components:
  schemas:
    FarmersMarket:
      type: object
      properties:
        id:
          type: string
          format: uuid
        Name:
          type: string
        operatingDay:
          type: array
          items:
            $ref: '#/components/schemas/OperatingDay'
        operatingMonths:
          type: array
          items:
            type: string
        phone:
          type: string
        streetAddress:
          type: string
        city:
          type: string
        state:
          type: string
        zipCode:
          type: string
        email:
          type: string
          format: email
        website:
          type: string
        socialMedia:
          type: array
          items:
            $ref: '#/components/schemas/SocialMedia'
    SocialMedia:
      type: object
      properties:
        links:
          type: string
    OperatingDay:
      type: object
      properties:
        day:
          type: string
        operatingHours:
          type: string
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        FarmersMarkets:
          type: array
          items:
            $ref: '#/components/schemas/FarmersMarket'
  
