/**
 * Farmer's Markets - OpenAPI 3.0
 * Does cool stuff
 *
 * OpenAPI spec version: 1.0.11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SocialMedia } from './socialMedia';

export interface FarmersMarket { 
    id?: string;
    name?: string;
    isSnapFriendly?: boolean;
    operatingHours?: string;
    operatingDays?: string;
    operatingMonths?: string;
    phone?: string;
    streetAddress?: string;
    city?: string;
    state?: string;
    zipCode?: string;
    email?: string;
    website?: string;
    socialMedia?: Array<SocialMedia>;
}